# Variance Reduction in Monte Carlo methods

# 1. Importance sampling
#Instead of evaluate E_{f}[g(X)]=???_{A}g(x)f(x)dx this method includes a candidate or auxiliar density h(x),
#E_{f}[g(X)]=???_{A}g(x)*(f(x)/h(x))* h(x)dx=E_{h}[g(X)f(X)/h(X)]

#E_{f}[g(X)]???(1/n)???_{i}^{n} g(yi){f(yi)/h(yi)},where y1,y2,…,yn are generated by pdf h.

#The candidate h should be chosen as to satisfy as much as possible: h(x)???|g(x)|f(x).
#The restrictions are:
#1.The variance of gf/h must be finite (the tails of h must be higher than those of f)
#2.The support of h must include the support of f
#This is the same idea of the accept-reject method.

#The importance-sampling function in R:

# rh generates samples from candidate pdf
i.sampling <- function(f, g, h, rh, n=1e4) {
  ys <- rh(n)
  mean(g(ys)*f(ys)/h(ys))
}

#ex.1 
#Let X~N(0,1) estimate P(X>4.5)
# our target pdf will be th expo pdf truncated at 4.5 
#h(x)=e^(-x)/ int_{4.5}^{inf} e^(-x)dx =e^-(x-4.5)

xs <- seq(0.1,10,by=0.05)
plot(xs,dexp(xs),col="blue", type="l")   # the exponential pdf
lines(xs,exp(-(xs-4.5)),col="red",lwd=2) # the truncated pdf
abline(v=4.5,lty=2)
#Here’s a plot of the target pdf g (in blue) and the candidate pdf h (in red):
g <- dnorm
h <- function(x) exp(-(x-4.5))

xs <- seq(4.5,20,by=0.05)
plot(xs,g(xs),col="blue", type="l", ylim=c(0,0.5e-4))
lines(xs,h(xs),col="red",lwd=2)
# True value:
pnorm(4.5, lower.tail=FALSE)  # theta (could also be computed by 1-pnorm(4.5))
#[1] 3.397673e-06

# do the Importance Sampling
f  <- function(x) x/x         # uniform pdf
rh <- function(n) rexp(n)+4.5 # rexp() shifted to 4.5
i.sampling(f,g,h,rh)  #[1] 3.396767e-06

#ex.2
#Estimate the integral I(b)=int_{b}^{inf} e^(-x)*e^(-e^(-x))dx.
#Analytical solution is 1-e^(-e^(-b)).

x<-1:100

# the target density
f <- function(x){exp(-x)*exp(-exp(-x))} 

# the solution of integrate exp(-x)*exp(-exp(-x)) dx, x=b..Inf
solution <- function(b) 1-exp(-exp(-b))
plot(x,solution(x), type="l", col="red", ylim=c(0,0.01), lwd=2, xlab="b", ylab="I(b)")
# pick value for b
b <- min(which(solution(x)==0)) # first b where R underflows, so let's use this as an eg
b #[1] 38
plot(x,solution(x), type="l", col="red", ylim=c(0,0.01), lwd=2, xlab="b", ylab="I(b)")
abline(v=b,col="green",lty=2)
#candidate density f(X|xm,alpha)=(alpha*xm^alpha)/(x^(alpha+1))

alpha <- 4
h <- function(x,xm,alpha) alpha*xm^alpha/x^(alpha+1)

plot(x,solution(x), type="l", col="red", ylim=c(0,0.1), lwd=2, xlab="b", ylab="I(b)")
abline(v=b,col="green",lty=2)
lines(x, h(x, xm=b, alpha=alpha), col="blue", lwd=2)

#Notice how the candidate function (in blue) is above the target function (in red).
#Now we need to generate a random sample from the h pareto pdf. Random samples can be generated using inverse transform sampling 
# X=xm/U^(1/alpha)~ Pareto(xm,alpha) , U~U(0,1)
set.seed(101)
U <- runif(1000)
X <- b/U^(1/alpha) # alternative: library(VGAM); X <- rpareto(N,b,alpha)

mean(f(X)/h(X,xm=b,alpha=alpha)) # importance sampling
exp(-b)